export const services = {
  'complete_marriage_package': {
    order: 0,
    label: 'SIGNATURE OFFERING',
    name: 'Complete Marriage Package',
    title: 'Complete Marriage Package',
    body: 'Six personalized preparation sessions and a ceremony shaped by someone who already knows your story.',
    href: '/marriage-package',
    priceCents: 192500,
    isGiftable: true,
    requiresDeposit: true,
    image: {
      src: '/images/service-marriage.png',
      alt: 'An open journal, wedding rings, and a pencil on linen',
    },
  },
  'strong_start': {
    order: 1,
    label: 'PREPARE',
    name: 'The Strong Start Program',
    title: 'The Strong Start Program',
    body: 'Six-session marriage preparation',
    href: '/strong-start',
    priceCents: 95500,
    isGiftable: true,
    requiresDeposit: true,
  },
  'wedding_officiation': {
    order: 2,
    label: 'CELEBRATE',
    name: 'Wedding Officiation',
    title: 'Wedding Officiation',
    body: 'A meaningful ceremony tailored to your story.',
    href: '/services/wedding-officiation',
    priceCents: 59500,
    isGiftable: true,
    requiresDeposit: true,
  },
  'relationship_check_in': {
    order: 3,
    label: 'STRENGTHEN',
    name: 'Relationship Check-In',
    title: 'Relationship Check-In',
    body: 'A supportive space to connect, reflect & realign',
    href: '/relationship-check-in',
    priceCents: 0,
    isGiftable: false,
    requiresDeposit: false,
  },
  'grief_support': {
    order: 4,
    label: 'NAVIGATE',
    name: 'Grief & Bereavement Support',
    title: 'Grief & Bereavement Support',
    body: 'Compassionate support for your unique journey.',
    href: '/services/grief-support',
    priceCents: 0,
    isGiftable: false,
    requiresDeposit: false,
  },
  'funeral_memorial_officiation': {
    order: 5,
    label: 'NAVIGATE',
    name: 'Funeral & Memorial Services',
    title: 'Funeral & Memorial Services',
    body: 'Thoughtful, personalized services to honor a life.',
    href: '/services/funeral',
    priceCents: 40000,
    isGiftable: false,
    requiresDeposit: false,
  },
};
